export const registerItemTypeValues = [
  'WOMENSWEAR',
  'MENSWEAR',
  'CHILDRENSWEAR',
  'SHOES',
  'BAGS',
  'ACCESSORIES',
  'COSTUME_JEWELRY',
  'JEWELRY',
  'HOME_DECOR',
  'FURNITURE',
  'ELECTRONICS',
  'BOOKS',
  'TOYS',
  'KITCHENWARE',
  'MEDIA',
  'PERSONAL_CARE',
  'TOOLS_AND_EQUIPMENT',
  'KNICK_KNACKS',
] as const;

export type RegisterItemTypeValue = (typeof registerItemTypeValues)[number];

export const registerConfig = {
  defaultLogoImage: '/favicon.ico',
  defaultOpeningHours: ['Seg-Sab: 09:00-18:00'],
  defaultStoreSize: 'MEDIUM' as const,
  defaultItemRenewal: 'MONTHLY' as const,
  defaultAveragePrice: 0,
  defaultAverageQuantity: 0,
  defaultIsAcceptExchange: false,
  itemTypes: [
    { label: 'Roupas Femininas', value: 'WOMENSWEAR' },
    { label: 'Roupas Masculinas', value: 'MENSWEAR' },
    { label: 'Roupas Infantis', value: 'CHILDRENSWEAR' },
    { label: 'Calcados', value: 'SHOES' },
    { label: 'Bolsas', value: 'BAGS' },
    { label: 'Acessorios', value: 'ACCESSORIES' },
    { label: 'Bijuterias', value: 'COSTUME_JEWELRY' },
    { label: 'Joias', value: 'JEWELRY' },
    { label: 'Decoracao', value: 'HOME_DECOR' },
    { label: 'Moveis', value: 'FURNITURE' },
    { label: 'Eletronicos', value: 'ELECTRONICS' },
    { label: 'Livros', value: 'BOOKS' },
    { label: 'Brinquedos', value: 'TOYS' },
    { label: 'Itens para Casa', value: 'KITCHENWARE' },
    { label: 'Midia', value: 'MEDIA' },
    { label: 'Cuidados Pessoais', value: 'PERSONAL_CARE' },
    { label: 'Ferramentas e Equipamentos', value: 'TOOLS_AND_EQUIPMENT' },
    { label: 'Decorativos', value: 'KNICK_KNACKS' },
  ] as const,
};